import os
import pymongo
from datetime import datetime, timezone

MONGO_URI = os.getenv("MONGO_URI", os.getenv("MONGODB_URI", "mongodb+srv://kesav6442_db_user:F1wnTkeK5JJ4lvHe@cluster0.tlcbot1.mongodb.net/civicconnect_db?retryWrites=true&w=majority"))
DB_NAME = os.getenv("DB_NAME", os.getenv("MONGODB_DATABASE", "civicconnect_db"))

PROBLEMS_DATA = [
    {
        "id": "JH-CHLG-2026-1011",
        "title": "Severe Arsenic & Fluoride Contamination in Handpumps",
        "category": "Water Management",
        "domain": "Water Management",
        "district": "Sahebganj",
        "locationAddress": "Rajmahal Block, Ganga Basin Belt, Sahebganj",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Mukesh Soren",
        "citizenPhone": "+91 94311 11001",
        "citizenEmail": "mukesh.soren@jharkhandmail.in",
        "description": "Over 14 village shallow borewells and handpumps have detected arsenic levels 5x above WHO safety limits. Villagers exhibit early signs of keratosis and skin lesions. Urgent need for solar-powered modular arsenic adsorption filters.",
        "keywords": ["Arsenic contamination", "Water quality", "Adsorption filter", "Handpump", "Safe drinking water"],
        "mediaUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.985,
        "aiReason": "Critical water chemistry hazard posing severe epidemiological health risks to rural riverine populations."
    },
    {
        "id": "JH-CHLG-2026-1012",
        "title": "Uncontrolled Fly Ash & Coal Dust Smog Near Thermal Power Cluster",
        "category": "Environment",
        "domain": "Environment",
        "district": "Bokaro",
        "locationAddress": "Chandrapura Thermal Power Buffer Zone, Bokaro",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Anjali Kumari",
        "citizenPhone": "+91 94311 11002",
        "citizenEmail": "anjali.k@jharkhandmail.in",
        "description": "Dense ambient particulate matter (PM2.5 and PM10) from coal transit corridors and ash ponds exceeds 380 ug/m3. Schoolchildren and elderly residents are reporting acute respiratory infections. Need smart misting cannons and IoT particulate monitoring.",
        "keywords": ["Fly ash", "Air pollution", "PM2.5", "Coal dust suppression", "Thermal power emissions"],
        "mediaUrl": "https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.962,
        "aiReason": "High ambient particulate air pollution requiring industrial automated dust suppression and real-time sensor grids."
    },
    {
        "id": "JH-CHLG-2026-1013",
        "title": "Post-Harvest Cold Chain Deficiency for Lac and Mahua Collectors",
        "category": "Rural Livelihoods",
        "domain": "Rural Livelihoods",
        "district": "Khunti",
        "locationAddress": "Torpa & Karra Tribal Self-Help Group Hubs, Khunti",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Birsa Munda SHG Federation",
        "citizenPhone": "+91 94311 11003",
        "citizenEmail": "khunti.tribal.shg@jharkhandmail.in",
        "description": "Tribal lac and Minor Forest Produce (MFP) cultivators face 35% crop decay during monsoon storage due to high humidity and lack of decentralized solar-assisted dehumidified storage facilities. Requires low-cost solar cold micro-warehousing.",
        "keywords": ["Tribal livelihoods", "Lac cultivation", "Minor forest produce", "Solar cold storage", "SHG value addition"],
        "mediaUrl": "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.941,
        "aiReason": "High rural socio-economic impact challenge requiring decentralized renewable energy powered post-harvest storage."
    },
    {
        "id": "JH-CHLG-2026-1014",
        "title": "Frequent Elephant-Human Conflict along Forest Corridor",
        "category": "Environment",
        "domain": "Environment",
        "district": "Latehar",
        "locationAddress": "Betla National Park Periphery & Mahuadanr, Latehar",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Sanjay Oraon",
        "citizenPhone": "+91 94311 11004",
        "citizenEmail": "sanjay.oraon@jharkhandmail.in",
        "description": "Wild elephant herds traversing fragmented wildlife corridors repeatedly enter agricultural fields and villages, causing crop loss and casualties. Need an AI-powered thermal camera and acoustic early-warning detection network to alert villagers via SMS/sirens.",
        "keywords": ["Human wildlife conflict", "Elephant corridor", "Acoustic sensor", "Thermal camera early warning", "Forest buffer"],
        "mediaUrl": "https://images.unsplash.com/photo-1557050543-4d5f4e07ef46?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.978,
        "aiReason": "Critical life safety and biodiversity protection challenge requiring AI vision-based perimeter early detection."
    },
    {
        "id": "JH-CHLG-2026-1015",
        "title": "Subsurface Coal Seam Fires Causing Ground Subsidence",
        "category": "Urban Infrastructure",
        "domain": "Urban Infrastructure",
        "district": "Dhanbad",
        "locationAddress": "Jharia Coalfield Belt, Bastacolla Ward, Dhanbad",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Dhanbad Citizen Safety Forum",
        "citizenPhone": "+91 94311 11005",
        "citizenEmail": "jharia.safety@jharkhandmail.in",
        "description": "Underground coal seam smoldering produces high surface temperatures (>70C) and toxic CO/SO2 emissions, causing sudden fissures in roads and residential housing foundations. Requires drone thermal mapping and nitrogen foam injection stabilization.",
        "keywords": ["Mine fire", "Ground subsidence", "Jharia", "Thermal drone mapping", "Structural hazard"],
        "mediaUrl": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.992,
        "aiReason": "Critical structural integrity and civil safety hazard caused by smoldering coal strata requiring advanced geophysical monitoring."
    },
    {
        "id": "JH-CHLG-2026-1016",
        "title": "Flash Flooding and Heavy Siltation of Rural Check Dams",
        "category": "Agriculture",
        "domain": "Agriculture",
        "district": "Palamu",
        "locationAddress": "North Koel River Catchment, Daltonganj Rural, Palamu",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Rameshwar Singh",
        "citizenPhone": "+91 94311 11006",
        "citizenEmail": "rameshwar.singh@jharkhandmail.in",
        "description": "Seasonal check dams and reservoirs lose over 40% of their storage capacity within 2 seasons due to heavy red-soil erosion from upland deforestation. Farmers face severe drought in rabi season. Need automated silt traps and vegetative geo-textile bunding.",
        "keywords": ["Check dam siltation", "Soil erosion", "Rabi irrigation", "Water harvesting", "Watershed management"],
        "mediaUrl": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.954,
        "aiReason": "High-priority watershed degradation affecting agricultural water security in drought-prone Palamu."
    },
    {
        "id": "JH-CHLG-2026-1017",
        "title": "Maternal Anemia & Malnutrition Tele-Monitoring in Remote Anganwadis",
        "category": "Healthcare",
        "domain": "Healthcare",
        "district": "West Singhbhum",
        "locationAddress": "Saranda Forest Anganwadi Clusters, Chaibasa, West Singhbhum",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Saranda Maternal Health Mission",
        "citizenPhone": "+91 94311 11007",
        "citizenEmail": "maternal.saranda@jharkhandmail.in",
        "description": "High prevalence of severe maternal nutritional anemia among Ho and Santhal tribal mothers in deep forest pockets. Anganwadi workers lack non-invasive point-of-care digital hemoglobinometers and offline digital health tracking tablets.",
        "keywords": ["Maternal anemia", "Point-of-care diagnostics", "Non-invasive hemoglobinometer", "Anganwadi tele-health", "Tribal nutrition"],
        "mediaUrl": "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.981,
        "aiReason": "Critical public health priority requiring point-of-care non-invasive diagnostic tools in inaccessible rural pockets."
    },
    {
        "id": "JH-CHLG-2026-1018",
        "title": "Lack of Assistive Digital Infrastructure in Tribal Residential Schools",
        "category": "Education",
        "domain": "Education",
        "district": "Gumla",
        "locationAddress": "Eklavya Model Residential School, Bishunpur, Gumla",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Pooja Bhagat",
        "citizenPhone": "+91 94311 11008",
        "citizenEmail": "pooja.bhagat@jharkhandmail.in",
        "description": "Visually and hearing-impaired tribal students lack localized Kurukh/Mundari digital audio-visual learning tools, screen readers, and low-cost refreshable Braille displays in tribal model schools.",
        "keywords": ["Inclusive education", "Tribal language learning", "Braille assistive tech", "Smart classroom", "Disability access"],
        "mediaUrl": "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.923,
        "aiReason": "Medium-priority digital inclusion initiative for Divyang tribal school students."
    },
    {
        "id": "JH-CHLG-2026-1019",
        "title": "Contamination of Subarnarekha Tributary with Industrial Effluents",
        "category": "Water Management",
        "domain": "Water Management",
        "district": "Saraikela Kharsawan",
        "locationAddress": "Adityapur Industrial Area Outfall Channel, Saraikela Kharsawan",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Gopal Chandra Mahto",
        "citizenPhone": "+91 94311 11009",
        "citizenEmail": "gopal.mahto@jharkhandmail.in",
        "description": "Untreated metal plating and chemical effluents with heavy chromium/lead residues are released into agricultural drainages feeding into Subarnarekha River. Downstream cattle and crops are severely affected.",
        "keywords": ["Industrial effluent", "Heavy metal pollution", "Subarnarekha river", "Automated water monitoring", "Chromium remediation"],
        "mediaUrl": "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.989,
        "aiReason": "Critical environmental toxicity and industrial river pollution violation requiring automated effluent surveillance."
    },
    {
        "id": "JH-CHLG-2026-1020",
        "title": "Lack of Ramp Access & Tactile Pathways in Government District Hospital",
        "category": "Accessibility",
        "domain": "Accessibility",
        "district": "Hazaribagh",
        "locationAddress": "Sadar Hospital Complex, Main OPD Wing, Hazaribagh",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Divyang Welfare Society Hazaribagh",
        "citizenPhone": "+91 94311 11010",
        "citizenEmail": "divyang.hazaribagh@jharkhandmail.in",
        "description": "The multi-storey hospital OPD wing lacks gradient-compliant wheelchair ramps, tactile guidance paving for the blind, and disabled-friendly sanitary restrooms, forcing disabled patients to rely on manual carrying.",
        "keywords": ["Hospital accessibility", "Wheelchair ramps", "Tactile guidance", "Barrier-free infrastructure", "Divyangjan access"],
        "mediaUrl": "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.948,
        "aiReason": "High-priority public infrastructure barrier-free compliance under Accessible India guidelines."
    },
    {
        "id": "JH-CHLG-2026-1021",
        "title": "Unsegregated Open Dumping and Toxic Leachate Seepage",
        "category": "Waste Management",
        "domain": "Waste Management",
        "district": "Deoghar",
        "locationAddress": "Kunda Solid Waste Landfill Site, Deoghar",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Vikas Tiwari",
        "citizenPhone": "+91 94311 11011",
        "citizenEmail": "vikas.tiwari@jharkhandmail.in",
        "description": "During the Shravani Mela pilgrimage rush, over 80 metric tons of daily mixed municipal and plastic waste accumulates at open dump sites, generating foul leachate that infiltrates surrounding groundwater wells.",
        "keywords": ["Solid waste", "Leachate seepage", "Pilgrimage waste management", "Plastic bio-mining", "Deoghar"],
        "mediaUrl": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.959,
        "aiReason": "High-priority urban solid waste crisis aggravated by religious tourism surges requiring bio-methanation and decentralized segregation."
    },
    {
        "id": "JH-CHLG-2026-1022",
        "title": "Unreclaimed Mica Mine Abandoned Pits Threatening Rural Cattle and Children",
        "category": "Environment",
        "domain": "Environment",
        "district": "Koderma",
        "locationAddress": "Domchanch Forest Border Mica Belt, Koderma",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Ashok Yadav",
        "citizenPhone": "+91 94311 11012",
        "citizenEmail": "ashok.yadav@jharkhandmail.in",
        "description": "Dozens of deep open cast mica extraction trenches left un-reclaimed after illegal mining fill with stagnant rainwater, posing fatal drowning risks to children and livestock. Requires ecological backfilling and afforestation.",
        "keywords": ["Abandoned mine pits", "Mica belt", "Ecological reclamation", "Safety hazard", "Afforestation"],
        "mediaUrl": "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.938,
        "aiReason": "High physical hazard and environmental degradation caused by legacy non-reclaimed mining pits."
    },
    {
        "id": "JH-CHLG-2026-1023",
        "title": "Unstable High-Voltage Grid Outages Damaging Irrigation Pumps",
        "category": "Public Service Delivery",
        "domain": "Public Service Delivery",
        "district": "Garhwa",
        "locationAddress": "Ranka & Dhurki Agricultural Belt, Garhwa",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Kisan Kalyan Samiti Garhwa",
        "citizenPhone": "+91 94311 11013",
        "citizenEmail": "kisan.garhwa@jharkhandmail.in",
        "description": "Rural agricultural feeders experience severe voltage fluctuations (surging from 140V to 310V) causing burnouts of hundreds of submersible water pumps during peak sowing periods. Need smart microgrid voltage stabilizers.",
        "keywords": ["Voltage fluctuations", "Rural power grid", "Pump burnouts", "Microgrid stabilizer", "Power distribution"],
        "mediaUrl": "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.951,
        "aiReason": "High-priority rural utility infrastructure failure crippling seasonal agricultural output."
    },
    {
        "id": "JH-CHLG-2026-1024",
        "title": "Severe Soil Salinity and Acidification around Stone Crushing Units",
        "category": "Agriculture",
        "domain": "Agriculture",
        "district": "Pakur",
        "locationAddress": "Hiranpur & Malpahari Stone Quarry Corridor, Pakur",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Sanatan Murmu",
        "citizenPhone": "+91 94311 11014",
        "citizenEmail": "sanatan.murmu@jharkhandmail.in",
        "description": "Fine quartzite stone dust settling on surrounding paddy and mustard fields has altered soil pH and reduced crop yields by 45%. Farmers require soil conditioning bio-amendments and vegetative buffer zones.",
        "keywords": ["Stone dust", "Soil fertility", "Stone crushing units", "Biochar soil amendment", "Crop yield"],
        "mediaUrl": "https://images.unsplash.com/photo-1592417817098-8f3d6ef23ef9?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.915,
        "aiReason": "Medium-priority agricultural soil degradation caused by industrial mineral processing dust."
    },
    {
        "id": "JH-CHLG-2026-1025",
        "title": "Bridge Substructure Scour During Monsoonal Hill Torrent",
        "category": "Urban Infrastructure",
        "domain": "Urban Infrastructure",
        "district": "Ramgarh",
        "locationAddress": "Damodar River Crossing Bridge Pier 4, Mandu, Ramgarh",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Engineers Action Group Ramgarh",
        "citizenPhone": "+91 94311 11015",
        "citizenEmail": "civilsafety.ramgarh@jharkhandmail.in",
        "description": "High velocity turbulent monsoonal discharge in the Damodar river has exposed bridge foundation piles by 2.2 meters, threatening catastrophic structural collapse of the state highway link. Requires immediate gabion rip-rap and sensor strain monitoring.",
        "keywords": ["Bridge scouring", "Structural health monitoring", "Damodar river", "Highway bridge", "Civil collapse hazard"],
        "mediaUrl": "https://images.unsplash.com/photo-1545558014-8692077e9b5c?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.994,
        "aiReason": "Critical life safety and transportation lifeline failure risk requiring immediate structural reinforcement."
    },
    {
        "id": "JH-CHLG-2026-1026",
        "title": "Lack of Cold Storage for Silk (Tussar) Cocoon Farmers",
        "category": "Rural Livelihoods",
        "domain": "Rural Livelihoods",
        "district": "Godda",
        "locationAddress": "Sundarpahari & Boarijor Tribal Tussar Center, Godda",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Paharia Silk Weavers Society",
        "citizenPhone": "+91 94311 11016",
        "citizenEmail": "paharia.silk@jharkhandmail.in",
        "description": "Indigenous Paharia silkworm rearers suffer heavy losses when pupae hatch prematurely before processing due to heatwaves. A solar-powered micro-climate regulated cocoon preservation unit is needed.",
        "keywords": ["Tussar silk", "Cocoon preservation", "Tribal handloom", "Solar climate control", "Sericulture"],
        "mediaUrl": "https://images.unsplash.com/photo-1606787366850-de6330128bfc?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.932,
        "aiReason": "Medium-priority sericulture supply chain optimization for vulnerable tribal forest-dwellers."
    },
    {
        "id": "JH-CHLG-2026-1027",
        "title": "High Incidence of Waterborne Fluorosis and Skeletal Deformities",
        "category": "Water Management",
        "domain": "Water Management",
        "district": "Giridih",
        "locationAddress": "Tisri & Gawan Deep Aquifers, Giridih",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Pradeep Kumar Verma",
        "citizenPhone": "+91 94311 11017",
        "citizenEmail": "pradeep.verma@jharkhandmail.in",
        "description": "Over 200 children in Tisri block exhibit dental and skeletal fluorosis from drinking water with fluoride levels reaching 4.8 mg/L. Community-scale electrolytic defluoridation plants are urgently requested.",
        "keywords": ["Fluorosis", "Fluoride removal", "Electrolytic defluoridation", "Deep aquifer toxicity", "Giridih"],
        "mediaUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.987,
        "aiReason": "Critical waterborne public health emergency causing permanent skeletal and dental deformities."
    },
    {
        "id": "JH-CHLG-2026-1028",
        "title": "Poor Telecommunication Connectivity Crippling PDS Ration Biometrics",
        "category": "Public Service Delivery",
        "domain": "Public Service Delivery",
        "district": "Chatra",
        "locationAddress": "Pratappur & Hunterganj Deep Valley Villages, Chatra",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Chatra Rural Gram Sabha",
        "citizenPhone": "+91 94311 11018",
        "citizenEmail": "gram.chatra@jharkhandmail.in",
        "description": "Zero cellular signal in 18 hilly hamlets prevents Point-of-Sale (e-POS) biometric authentication for fair price ration grain distribution. Elderly beneficiaries walk 12 km to authenticate. Requires low-power offline mesh biometric syncing.",
        "keywords": ["PDS ration", "Biometric authentication", "Rural connectivity", "e-POS offline sync", "Public welfare delivery"],
        "mediaUrl": "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.966,
        "aiReason": "High-priority social welfare delivery bottleneck caused by rural telecom shadow zones."
    },
    {
        "id": "JH-CHLG-2026-1029",
        "title": "Severe Waterlogging and Raw Sewage Overflow in Ward 14",
        "category": "Sanitation",
        "domain": "Sanitation",
        "district": "East Singhbhum",
        "locationAddress": "Bagbera Colony Low-Lying Drainage Channel, Jamshedpur",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Bagbera Residents Welfare Committee",
        "citizenPhone": "+91 94311 11019",
        "citizenEmail": "bagbera.welfare@jharkhandmail.in",
        "description": "Inadequate storm drainage causes 3-foot deep raw sewage backflows into streets and ground floors during rains, creating intense vector-borne dengue and cholera outbreaks. Demands decentralized bio-digestive drain filtration.",
        "keywords": ["Urban waterlogging", "Sewage overflow", "Vector-borne disease", "Stormwater drainage", "Sanitation"],
        "mediaUrl": "https://images.unsplash.com/photo-1584467735815-f778f274e296?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.957,
        "aiReason": "High public health hazard from stagnant urban sewage inundation and epidemic risk."
    },
    {
        "id": "JH-CHLG-2026-1030",
        "title": "High Transmission Losses and Frequent Transformer Explosions in Agro Belt",
        "category": "Public Service Delivery",
        "domain": "Public Service Delivery",
        "district": "Lohardaga",
        "locationAddress": "Kisko & Senha Agricultural Substation, Lohardaga",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Maheshwar Sahu",
        "citizenPhone": "+91 94311 11020",
        "citizenEmail": "maheshwar.sahu@jharkhandmail.in",
        "description": "Overloaded 25 kVA distribution transformers burn out every 3 weeks due to unbalanced single-phase tapping. Farmers lose potato and vegetable cold storage supplies. Need smart auto-load balancer distribution units.",
        "keywords": ["Transformer failure", "Distribution loss", "Agro power supply", "Load balancer", "Rural electrification"],
        "mediaUrl": "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.949,
        "aiReason": "High-priority rural electricity distribution reliability challenge affecting horticulture cold preservation."
    },
    {
        "id": "JH-CHLG-2026-1031",
        "title": "Lack of Emergency Obstetric Care Ambulance Telemetry in Dense Hillocks",
        "category": "Healthcare",
        "domain": "Healthcare",
        "district": "Simdega",
        "locationAddress": "Kolebira & Bano Hill Tribal Blocks, Simdega",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Simdega Community Health Network",
        "citizenPhone": "+91 94311 11021",
        "citizenEmail": "health.simdega@jharkhandmail.in",
        "description": "Pregnant mothers in interior tribal hamlets face 3+ hours transport delay to the nearest First Referral Unit (FRU). 108 ambulances lack satellite telemetry for fetal heart monitoring and vital sign relay during transport.",
        "keywords": ["Emergency ambulance", "Obstetric telemetry", "Maternal mortality", "Satellite tele-health", "Rural emergency"],
        "mediaUrl": "https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.982,
        "aiReason": "Critical life-saving emergency healthcare transport infrastructure gap in undulating tribal terrain."
    },
    {
        "id": "JH-CHLG-2026-1032",
        "title": "Loss of Indigenous Medicinal Plant Species Due to Forest Fires",
        "category": "Environment",
        "domain": "Environment",
        "district": "Dumka",
        "locationAddress": "Kathikund & Shikaripara Hill Reserves, Dumka",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Traditional Vaidya Association Dumka",
        "citizenPhone": "+91 94311 11022",
        "citizenEmail": "vaidya.dumka@jharkhandmail.in",
        "description": "Seasonal uncontrolled mahua flower gathering fires burn undergrowth and endanger rare Santhal medicinal plants like Sarpagandha and Chirata. Need low-cost IoT smoke sensor beacons and community fire-breaks.",
        "keywords": ["Forest fire detection", "Medicinal plants", "Biodiversity conservation", "IoT smoke beacon", "Tribal traditional medicine"],
        "mediaUrl": "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.925,
        "aiReason": "Medium-priority botanical biodiversity protection and forest fire early warning system."
    },
    {
        "id": "JH-CHLG-2026-1033",
        "title": "Cyber Fraud Targeting Rural Bank Customers via Fake Aadhaar Biometrics",
        "category": "Public Service Delivery",
        "domain": "Public Service Delivery",
        "district": "Jamtara",
        "locationAddress": "Narayanpur & Karmatanr Customer Service Points, Jamtara",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Prashant Mandal",
        "citizenPhone": "+91 94311 11023",
        "citizenEmail": "prashant.mandal@jharkhandmail.in",
        "description": "Fraudulent silicon fingerprint spoofing at local banking correspondent CSP kiosks has resulted in illegal DBT pension withdrawals from illiterate tribal beneficiaries. Requires liveness detection in micro-ATMs.",
        "keywords": ["Biometric spoofing", "Cyber fraud", "Aadhaar Enabled Payment System", "AePS liveness detection", "Citizen financial safety"],
        "mediaUrl": "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.971,
        "aiReason": "High-priority civic financial security vulnerability harming poor rural social security beneficiaries."
    },
    {
        "id": "JH-CHLG-2026-1034",
        "title": "Lack of Direct Market Access and Cold Storage for Strawberry & Dragonfruit",
        "category": "Agriculture",
        "domain": "Agriculture",
        "district": "Ranchi",
        "locationAddress": "Ormanjhi & Angara High-Value Crop Cluster, Ranchi",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Ranchi Progressive Horticulture Group",
        "citizenPhone": "+91 94311 11024",
        "citizenEmail": "horticulture.ranchi@jharkhandmail.in",
        "description": "Progressive smallholders adopting strawberry and exotic dragonfruit face distress sales to middlemen at 70% below wholesale mandi prices due to lack of pack-houses and cold logistics within 15 km.",
        "keywords": ["Horticulture market link", "Dragonfruit cold chain", "Farmer producer company", "Direct-to-market portal", "Ranchi"],
        "mediaUrl": "https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.936,
        "aiReason": "Medium-priority agricultural market linkage and value realization challenge for high-value crops."
    },
    {
        "id": "JH-CHLG-2026-1035",
        "title": "Severe Siltation and Eutrophication of Historical Water Tank",
        "category": "Water Management",
        "domain": "Water Management",
        "district": "Deoghar",
        "locationAddress": "Shivaganga Holy Water Reservoir, Temple Precinct, Deoghar",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Deoghar Heritage Conservation Trust",
        "citizenPhone": "+91 94311 11025",
        "citizenEmail": "heritage.deoghar@jharkhandmail.in",
        "description": "Mass bathing and ritual offerings cause massive algal blooms, oxygen depletion, and foul odors in the holy water tank, causing dermal infections among thousands of pilgrims. Demands solar-powered floating nanobubble aerators.",
        "keywords": ["Water reservoir restoration", "Algae control", "Nanobubble aeration", "Pilgrimage hygiene", "Water quality"],
        "mediaUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.963,
        "aiReason": "High-priority ecological water quality and sanitation challenge at high-density pilgrimage precinct."
    },
    {
        "id": "JH-CHLG-2026-1036",
        "title": "High Heavy-Vehicle Coal Freight Potholes and Bridge Deck Degradation",
        "category": "Roads",
        "domain": "Roads",
        "district": "Dhanbad",
        "locationAddress": "Govindpur-Sahibganj Coal Transit Highway KM 24-32, Dhanbad",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Dhanbad Transport Safety Association",
        "citizenPhone": "+91 94311 11026",
        "citizenEmail": "transportsafety.dhanbad@jharkhandmail.in",
        "description": "Continuous 40-tonne overloaded multi-axle coal dumper traffic has created 1.5-meter crater potholes, causing frequent tipper turnovers and fatal two-wheeler collisions. Requires steel-slag reinforced cold mix asphalt resurfacing.",
        "keywords": ["Road damage", "Coal transport corridor", "Pothole repair", "Steel slag asphalt", "Highway safety"],
        "mediaUrl": "https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.969,
        "aiReason": "High vehicular safety risk and heavy freight highway degradation requiring industrial waste-modified paving."
    },
    {
        "id": "JH-CHLG-2026-1037",
        "title": "Microplastic & Synthetic Silt Accumulation in Dimna Lake Catchment",
        "category": "Environment",
        "domain": "Environment",
        "district": "East Singhbhum",
        "locationAddress": "Dimna Lake Buffer Catchment Zone, Jamshedpur",
        "urgency": "High",
        "priority": "High",
        "citizenName": "Jamshedpur Green Earth Society",
        "citizenPhone": "+91 94311 11027",
        "citizenEmail": "green.jamshedpur@jharkhandmail.in",
        "description": "Tourist picnicking and upstream runoff have accumulated tons of microplastics and discarded plastic bottles along the feeder streams of Dimna Lake, the primary source of city potable water. Requires automated floating trash booms.",
        "keywords": ["Microplastics", "Lake conservation", "Potable water catchment", "Floating trash boom", "Water clean-up"],
        "mediaUrl": "https://images.unsplash.com/photo-1530587191325-3db32d826c18?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.952,
        "aiReason": "High environmental contamination risk to the metropolitan drinking reservoir."
    },
    {
        "id": "JH-CHLG-2026-1038",
        "title": "Lack of Automated Weather Stations for Micro-Climate Frost Alerts",
        "category": "Agriculture",
        "domain": "Agriculture",
        "district": "Latehar",
        "locationAddress": "Netarhat Plateau Horticultural Farms, Latehar",
        "urgency": "Medium",
        "priority": "Medium",
        "citizenName": "Netarhat Pear & Apple Growers Collective",
        "citizenPhone": "+91 94311 11028",
        "citizenEmail": "netarhat.farms@jharkhandmail.in",
        "description": "Unpredicted winter night frost drops temperatures below 0C on the high-altitude plateau, wiping out 60% of flowering pear and subtropical apple orchards. Requires IoT micro-climate automated weather stations sending SMS frost warnings.",
        "keywords": ["Frost warning", "Horticulture", "Micro-climate station", "Netarhat plateau", "Agricultural IoT"],
        "mediaUrl": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.928,
        "aiReason": "Medium-priority agricultural sensor technology implementation for temperate plateau fruit farmers."
    },
    {
        "id": "JH-CHLG-2026-1039",
        "title": "Unsafe Drinking Water in Primary Schools Due to Iron & Turbidity",
        "category": "Water Management",
        "domain": "Water Management",
        "district": "Hazaribagh",
        "locationAddress": "Barhi Block Govt Primary Schools Cluster, Hazaribagh",
        "urgency": "High",
        "priority": "High",
        "citizenName": "School Management Committee Federation",
        "citizenPhone": "+91 94311 11029",
        "citizenEmail": "smc.hazaribagh@jharkhandmail.in",
        "description": "Deep borewells in 12 rural primary schools pump dark reddish water with iron concentration >3.5 mg/L and high turbidity. Students drink boiled or contaminated water, leading to recurrent gastrointestinal illness. Need gravity sand-gravel terracotta iron filters.",
        "keywords": ["School drinking water", "Iron removal filter", "Midday meal hygiene", "Water turbidity", "Hazaribagh"],
        "mediaUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.967,
        "aiReason": "High child health and school sanitation vulnerability requiring low-maintenance gravity filtration."
    },
    {
        "id": "JH-CHLG-2026-1040",
        "title": "Bio-Medical Waste Open Burning Behind Community Health Center",
        "category": "Waste Management",
        "domain": "Waste Management",
        "district": "Bokaro",
        "locationAddress": "Bermo Sub-Divisional Hospital Premises, Bokaro",
        "urgency": "Critical",
        "priority": "Critical",
        "citizenName": "Bermo Nagarik Suraksha Parishad",
        "citizenPhone": "+91 94311 11030",
        "citizenEmail": "bermo.safety@jharkhandmail.in",
        "description": "Used syringes, blood-contaminated bandages, and expired pharmaceutical vials are dumped and burned in the open yard behind the hospital due to absence of common bio-medical waste treatment facility (CBWTF) pickup. Urgent need for temperature-controlled shredder-autoclave unit.",
        "keywords": ["Biomedical waste", "Open burning hazard", "Hospital infection control", "Autoclave disposal", "Bokaro"],
        "mediaUrl": "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
        "aiConfidenceValue": 0.991,
        "aiReason": "Critical bio-hazard and airborne pathogen emission violation requiring urgent institutional biomedical containment."
    }
]

def seed_30_problems():
    print(f"Connecting to MongoDB at {MONGO_URI.split('@')[-1]}...")
    client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
    db = client[DB_NAME]

    inserted_count = 0
    now_iso = datetime.now(timezone.utc).isoformat()

    for item in PROBLEMS_DATA:
        prob_id = item["id"]
        prob_doc = {
            "_id": prob_id,
            "id": prob_id,
            "title": item["title"],
            "category": item["category"],
            "domain": item["domain"],
            "description": item["description"],
            "district": item["district"],
            "locationAddress": item["locationAddress"],
            "urgency": item["urgency"],
            "priority": item["priority"],
            "submissionDate": "2026-09-25",
            "createdAt": now_iso,
            "citizenName": item["citizenName"],
            "citizenPhone": item["citizenPhone"],
            "citizenEmail": item["citizenEmail"],
            "status": "Pending Admin Review",
            "approvalStatus": "PENDING_ADMIN_REVIEW",
            "aiStatus": "AI_COMPLETED",
            "aiConfidence": f"{int(item['aiConfidenceValue'] * 1000) / 10}%",
            "aiConfidenceValue": item["aiConfidenceValue"],
            "aiReason": item["aiReason"],
            "aiSeverity": item["urgency"],
            "aiImpact": f"High socio-civic impact across {item['district']}",
            "aiModelVersion": "CivicConnect Master Multimodal Pipeline v5.2.0",
            "duplicateStatus": "Unique (0% duplicate match)",
            "possibleDuplicate": False,
            "aiVerification": "Valid",
            "needsHumanReview": False,
            "matchedUniversitiesCount": 0,
            "solutionsCount": 0,
            "keywords": item["keywords"],
            "mediaType": "image",
            "mediaUrl": item["mediaUrl"],
            "_class": "gov.jharkhand.civicconnect.model.Problem"
        }

        db.problems.replace_one({"_id": prob_id}, prob_doc, upsert=True)

        # Seed AI Analysis document
        ai_doc = {
            "_id": f"AI-{prob_id}",
            "id": f"AI-{prob_id}",
            "problemId": prob_id,
            "category": item["category"],
            "domain": item["domain"],
            "urgency": item["urgency"],
            "confidence": item["aiConfidenceValue"],
            "needsHumanReview": False,
            "verificationRecommendation": item["aiReason"],
            "modelVersion": "CivicConnect Master Multimodal Pipeline v5.2.0",
            "analyzedAt": now_iso,
            "_class": "gov.jharkhand.civicconnect.model.AIAnalysis"
        }
        db.ai_analysis.replace_one({"_id": ai_doc["_id"]}, ai_doc, upsert=True)

        inserted_count += 1
        print(f"[{inserted_count}/30] Successfully registered: {prob_id} - '{item['title']}' ({item['district']}) [{item['category']}]")

    print(f"\n[SUCCESS] All {inserted_count} citizen problems successfully added to MongoDB database ({DB_NAME})!")

if __name__ == "__main__":
    seed_30_problems()
