package gov.jharkhand.civicconnect.mcp;

import org.springframework.stereotype.Service;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Base64;
import java.util.HexFormat;
import java.util.List;
import java.util.Optional;

@Service
public class McpTokenService {

    private final McpTokenRepository tokenRepository;
    private final McpServerConfig serverConfig;
    private final McpAuditService auditService;
    private final SecureRandom secureRandom = new SecureRandom();

    public static final List<String> DEFAULT_MCP_SCOPES = List.of(
            "READ_PROBLEMS",
            "ANALYZE_PROBLEMS",
            "READ_PROJECTS",
            "READ_ANALYTICS"
    );

    public record TokenGenerationResult(
            String id,
            String plainTextToken,
            String tokenPrefix,
            String tokenMasked,
            Instant createdAt,
            Instant expiresAt,
            List<String> scopes
    ) {}

    public McpTokenService(McpTokenRepository tokenRepository, McpServerConfig serverConfig, McpAuditService auditService) {
        this.tokenRepository = tokenRepository;
        this.serverConfig = serverConfig;
        this.auditService = auditService;
    }

    /**
     * Generates a new cryptographically secure MCP Bearer token.
     * The plaintext token is returned ONLY in the result of this call and never stored in MongoDB.
     */
    public TokenGenerationResult generateToken(String adminUsername, List<String> scopes) {
        String rawToken = generateSecureRandomToken();
        String tokenHash = hashToken(rawToken);
        String tokenPrefix = rawToken.substring(0, Math.min(14, rawToken.length())) + "...";

        Instant now = Instant.now();
        Instant expiresAt = now.plus(serverConfig.getTokenExpiryDays(), ChronoUnit.DAYS);
        List<String> activeScopes = (scopes != null && !scopes.isEmpty()) ? scopes : DEFAULT_MCP_SCOPES;

        McpToken mcpToken = new McpToken(tokenHash, tokenPrefix, adminUsername, expiresAt, activeScopes);
        McpToken saved = tokenRepository.save(mcpToken);

        auditService.logEvent(
                McpAuditService.McpAuditEvent.MCP_TOKEN_CREATED,
                adminUsername,
                "ADMIN",
                "generateToken",
                saved.getId(),
                "SUCCESS",
                0,
                "Generated new secure MCP bearer token"
        );

        return new TokenGenerationResult(
                saved.getId(),
                rawToken,
                saved.getTokenPrefix(),
                saved.getTokenMasked(),
                saved.getCreatedAt(),
                saved.getExpiresAt(),
                saved.getScopes()
        );
    }

    /**
     * Regenerates token by revoking all existing active tokens and creating a brand new one.
     */
    public TokenGenerationResult regenerateToken(String adminUsername, List<String> scopes) {
        revokeAllActiveTokens(adminUsername, "Regenerated by Admin");

        TokenGenerationResult result = generateToken(adminUsername, scopes);

        auditService.logEvent(
                McpAuditService.McpAuditEvent.MCP_TOKEN_REGENERATED,
                adminUsername,
                "ADMIN",
                "regenerateToken",
                result.id(),
                "SUCCESS",
                0,
                "Regenerated MCP token and revoked previous active tokens"
        );

        return result;
    }

    /**
     * Revokes all active tokens.
     */
    public boolean revokeAllActiveTokens(String adminUsername, String reason) {
        List<McpToken> activeTokens = tokenRepository.findByActiveTrue();
        if (activeTokens.isEmpty()) {
            return false;
        }

        Instant now = Instant.now();
        for (McpToken token : activeTokens) {
            token.setActive(false);
            token.setRevokedAt(now);
            tokenRepository.save(token);

            auditService.logEvent(
                    McpAuditService.McpAuditEvent.MCP_TOKEN_REVOKED,
                    adminUsername,
                    "ADMIN",
                    "revokeToken",
                    token.getId(),
                    "SUCCESS",
                    0,
                    "Reason: " + (reason != null ? reason : "Admin Revocation")
            );
        }
        return true;
    }

    /**
     * Validates an incoming bearer token.
     * Verifies existence of active hash, expiration, and updates lastUsedAt timestamp.
     */
    public Optional<McpToken> validateBearerToken(String bearerToken) {
        if (bearerToken == null || !bearerToken.startsWith("civic_mcp_")) {
            return Optional.empty();
        }

        String hash = hashToken(bearerToken);
        Optional<McpToken> tokenOpt = tokenRepository.findByTokenHashAndActiveTrue(hash);

        if (tokenOpt.isEmpty()) {
            return Optional.empty();
        }

        McpToken token = tokenOpt.get();
        if (token.getExpiresAt() != null && token.getExpiresAt().isBefore(Instant.now())) {
            token.setActive(false);
            tokenRepository.save(token);
            return Optional.empty();
        }

        if (token.getRevokedAt() != null) {
            token.setActive(false);
            tokenRepository.save(token);
            return Optional.empty();
        }

        token.setLastUsedAt(Instant.now());
        tokenRepository.save(token);
        return Optional.of(token);
    }

    public Optional<McpToken> getActiveTokenMetadata() {
        return tokenRepository.findByActiveTrue().stream().findFirst();
    }

    public Optional<McpToken> getLatestTokenMetadata() {
        return tokenRepository.findFirstByOrderByCreatedAtDesc();
    }

    public String hashToken(String rawToken) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(rawToken.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(digest);
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("SHA-256 algorithm unavailable for token hashing", e);
        }
    }

    private String generateSecureRandomToken() {
        byte[] randomBytes = new byte[32];
        secureRandom.nextBytes(randomBytes);
        String randomStr = Base64.getUrlEncoder().withoutPadding().encodeToString(randomBytes);
        return "civic_mcp_" + randomStr.replaceAll("[^a-zA-Z0-9]", "x");
    }
}
